# Generated by Django 6.1.1 on 2026-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
