# Generated by Django 5.2.17 on 2026-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contract_id_alter_job_id_alter_proposal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
