"use client";import {useEffect,useState} from "react";import Link from "next/link";import {api,auth} from "../../lib/api";
const S=["hired","funded","working","delivered","paid"],L=["Hired","Funded","Working","Delivered","Paid"];
const D=["The employer chose the freelancer","Money is held safely in escrow","The freelancer is doing the work","Work submitted for review","Payment released to the freelancer"];
const NEXT={hired:["employer","deposit","Pay into escrow"],funded:["freelancer","start","Start work"],working:["freelancer","deliver","Submit delivery"],delivered:["employer","approve","Approve and release payment"]};
export default function Escrow(){const [cs,setCs]=useState(null);const [sel,setSel]=useState(null);const [err,setErr]=useState("");const [me,setMe]=useState(null);const [rt,setRt]=useState(5);const [rc,setRc]=useState("");const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);
const load=()=>api("/contracts/").then(d=>{setCs(d);const w=new URLSearchParams(location.search).get("id");setSel(s=>s||(w?+w:d[0]?.id))}).catch(e=>setErr(e.message));
useEffect(()=>{setMe(auth.user());load()},[]);
const c=cs?.find(x=>x.id===sel);const act=async a=>{setBusy(true);try{await api(`/contracts/${c.id}/${a}/`,{method:"POST"});setErr("");await load()}catch(e){setErr(e.message)}setBusy(false)};
const rev=()=>api(`/contracts/${c.id}/review/`,{method:"POST",body:{rating:rt,comment:rc}}).then(()=>setDone(true)).catch(e=>setErr(e.message));
if(err&&!cs)return <div className="card"><h2>Please log in</h2><p className="err">{err}</p><Link className="btn" href="/login">Log in</Link></div>;if(!cs)return <p>Loading...</p>;
if(!c)return <div className="card empty"><div style={{fontSize:44}}>🔒</div><h3>No escrow yet</h3><p className="mute">Hire a freelancer from a job's proposals to start a protected payment.</p><Link className="btn" href="/jobs">Browse jobs</Link></div>;
const i=S.indexOf(c.stage),n=NEXT[c.stage],mine=n&&me?.role===n[0],held=["funded","working","delivered"].includes(c.stage);
return(<><div className="pg-head"><div style={{flex:1}}><span className="mute">Escrow · Contract #{c.id}</span><h1 style={{margin:0}}>{c.job_title}</h1></div>{cs.length>1&&<select style={{maxWidth:240}} value={sel} onChange={e=>setSel(+e.target.value)}>{cs.map(x=><option key={x.id} value={x.id}>{x.job_title}</option>)}</select>}</div>
<div className="twocol"><div className="card"><h3>Progress</h3><div className="vsteps">{L.map((x,k)=>{const st=c.stage==="paid"||k<i?"d":k===i&&c.stage!=="disputed"?"c":"";return <div key={x} className={"vs "+st}><span className="dot">{st==="d"?"✓":k+1}</span><div><b>{x}</b><p>{D[k]}</p></div></div>})}</div></div>
<div><div className="card amt"><span className="mute">{c.stage==="paid"?"Paid out":held?"Held safely in escrow":c.stage==="disputed"?"Frozen":"Waiting for deposit"}</span><h1 style={{margin:"4px 0 10px"}}>₹{c.amount.toLocaleString("en-IN")}</h1>
{c.stage==="disputed"&&<p className="err">Dispute raised. Money is frozen until an admin decides.</p>}
{n&&(mine?<button className="btn big" disabled={busy} onClick={()=>act(n[1])}>{busy?"Please wait...":n[2]}</button>:<div className="wait">⏳ Waiting for the {n[0]} to act. You are logged in as {me?.role}.</div>)}
{held&&<p style={{marginTop:12}}><button onClick={()=>act("dispute")}>Raise a dispute</button></p>}{err&&<p className="err">{err}</p>}</div>
{c.stage==="paid"&&<div className="card"><h3>Leave a review</h3>{done?<p className="okmsg">Review submitted. Thank you!</p>:<><select value={rt} onChange={e=>setRt(+e.target.value)}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{"★".repeat(x)}</option>)}</select><textarea rows={2} placeholder="How did it go?" value={rc} onChange={e=>setRc(e.target.value)} style={{marginTop:8}}/><p><button className="btn" onClick={rev}>Submit review</button></p></>}</div>}
<div className="card"><h3>Transactions</h3>{c.transactions.length?c.transactions.map(t=><div className="tx" key={t.id}><span className="badge">{t.kind}</span><b>₹{t.amount.toLocaleString("en-IN")}</b><span className="mute">ref {t.gateway_ref}</span></div>):<p className="mute">No payments yet.</p>}</div></div></div></>)}
