import Link from "next/link";import JobCard from "../components/JobCard";import Avatar from "../components/Avatar";import Icon,{I} from "../components/Icon";import Counter from "../components/Counter";import {jobs,people,cats} from "../lib/data";
export default function Home(){return(<>
<section className="hero"><div className="heroL"><span className="pill">Escrow built in · Hindi first</span><h1 className="hi1">काम भी,<br/>भरोसा भी.</h1>
<p className="sub">India's freelance marketplace where small-city talent meets local business, and every rupee waits safely until the work is approved.</p>
<form action="/jobs" className="search"><input name="q" placeholder="Try: logo designer, Hindi typist, reels editor"/><button className="btn">Search</button></form>
<div className="row"><Link className="btn" href="/post">Post a job</Link><Link className="btn white" href="/jobs">Find work</Link></div>
<div className="trust"><span>✓ Free to join</span><span>✓ Escrow-protected</span><span>✓ Hindi support</span></div></div>
<div className="heroR"><svg viewBox="0 0 520 380" role="img" aria-label="A bridge connecting a freelancer and an employer, with money held in escrow in the middle">
<path d="M95 190 Q260 -30 425 190" fill="none" stroke="#14110F" strokeWidth="5" strokeDasharray="2 12" strokeLinecap="round"/>
<line x1="230" y1="92" x2="230" y2="300" stroke="#14110F" strokeWidth="3"/><line x1="290" y1="92" x2="290" y2="300" stroke="#14110F" strokeWidth="3"/>
<rect x="14" y="296" width="492" height="12" rx="6" fill="#14110F"/>
<g transform="translate(10 196)"><rect width="170" height="92" rx="14" fill="#fff" stroke="#14110F" strokeWidth="3"/><circle cx="34" cy="34" r="19" fill="#E5195A"/><text x="34" y="41" textAnchor="middle" fill="#fff" fontWeight="800" fontSize="19">P</text><text x="62" y="31" fontWeight="800" fontSize="16">Priya</text><text x="62" y="49" fontSize="12" fill="#5b524a">Designer</text><text x="14" y="78" fontSize="12" fontWeight="700">★ 4.9 · 23 reviews</text></g>
<g transform="translate(340 196)"><rect width="170" height="92" rx="14" fill="#fff" stroke="#14110F" strokeWidth="3"/><circle cx="34" cy="34" r="19" fill="#FFB800" stroke="#14110F" strokeWidth="2"/><text x="34" y="41" textAnchor="middle" fontWeight="800" fontSize="19">R</text><text x="62" y="31" fontWeight="800" fontSize="16">Rahul</text><text x="62" y="49" fontSize="12" fill="#5b524a">Bakery owner</text><text x="14" y="78" fontSize="12" fontWeight="700">Needs a logo</text></g>
<g transform="translate(165 44)"><rect width="190" height="66" rx="14" fill="#E5195A" stroke="#14110F" strokeWidth="3"/><text x="95" y="30" textAnchor="middle" fill="#fff" fontWeight="800" fontSize="24">₹3,000</text><text x="95" y="51" textAnchor="middle" fill="#fff" fontSize="12" fontWeight="700">held safely in escrow</text></g>
<rect x="190" y="326" width="140" height="36" rx="18" fill="#14110F"/><text x="260" y="350" textAnchor="middle" fill="#fff" fontSize="14" fontWeight="700">Approve → Pay</text></svg></div></section>
<div className="ticker"><div>{[...Array(2)].flatMap(()=>["Logo design","Hindi typing","React","Video editing","Translation","Packaging","Content writing","Reels","Canva","Data entry"]).map((x,i)=><span key={i}>✦ {x}</span>)}</div></div>
<section className="stats">{[["12,000+","Freelancers"],["₹2.4 Cr","Paid via escrow"],["4.8 ★","Average rating"],["22","Indian languages"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</section>
<h2>Browse by category</h2><div className="grid5">{cats.map(([n,d,p])=><Link key={n} href="/jobs" className="card hov cat"><span className="ic"><Icon d={p} size={26}/></span><h3>{n}</h3><p className="mute">{d}</p></Link>)}</div>
<h2 style={{marginTop:32}}>How escrow keeps you safe</h2><div className="grid">{[["Employer deposits","Money is held by HindWork, not given yet."],["Freelancer works","Work starts knowing payment is secured."],["Approve and release","Happy? Release. Not happy? Raise a dispute."]].map(([t,d],i)=><div className="card" key={t}><span className="num">{i+1}</span><h3>{t}</h3><p className="mute">{d}</p></div>)}</div>
<h2 style={{marginTop:32}}>Top freelancers</h2><div className="grid">{people.map(p=><Link key={p.id} href={`/freelancers/${p.id}`} className="card hov"><div className="row"><Avatar name={p.name} i={p.id}/><div><h3>{p.name}</h3><span className="mute">{p.city} · ₹{p.rate}/hr</span></div></div><p className="row" style={{margin:"8px 0"}}><span className="gstar"><Icon d={I.star} size={16}/></span><b>{p.rating}</b><span className="mute">({p.reviews} reviews)</span></p>{p.skills.slice(0,3).map(s=><span className="pill" key={s}>{s}</span>)}</Link>)}</div>
<div className="rowh"><h2>Latest jobs</h2><Link href="/jobs" className="lnk">See all jobs</Link></div>{jobs.slice(0,3).map(j=><JobCard key={j.id} j={j}/>)}
<section className="manifesto"><span className="insight">💡 AI insight<em>Design jobs in Roorkee rose 18% this month.</em></span><h2>Skill creates opportunity.<br/>Trust creates deals.<br/>Escrow creates confidence.</h2><p className="mute">Every rupee is protected from the first message to the final approval.</p></section>
<h2>Success stories</h2><div className="grid">{[["Priya, designer, Roorkee","Went from 0 to 23 clients in 6 months. Payments arrive the day work is approved.","₹48,000 earned","P"],["Rahul, bakery owner","Posted in Hindi, got 9 proposals in one day, and never worried about paying a stranger.","Logo done in 4 days","R"],["Sneha, translator, Pune","The AI suggested Marathi jobs I never would have found. My rate went up twice.","Rate up 40%","S"]].map(([n,q,r,l],i)=><div className="card story" key={n}><span className="tag">{r}</span><p>"{q}"</p><div className="row"><Avatar name={n} i={i}/><b>{n}</b></div></div>)}</div>
<h2 style={{marginTop:34}}>Work across every domain</h2><div className="row">{["Local shops and bakeries","Startups and apps","Education and tutoring","Agriculture and handicrafts","Healthcare content","Weddings and events","Real estate","Fitness and wellness"].map(x=><span className="chip" key={x}>{x}</span>)}</div>
<h2 style={{marginTop:34}}>Questions people ask</h2>{[["Is my money safe?","Yes. Employers deposit into escrow first. Money is released only after approval, or after an admin settles a dispute."],["Do I need English?","No. You can sign up, search and post jobs in Hindi and other Indian languages. Voice posting is supported."],["What does it cost?","Joining is free. A small service fee applies only when a job is completed and paid."],["What if the work is bad?","Raise a dispute. Funds stay frozen while our team reviews the chat, files and milestones."]].map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><p className="mute">{a}</p></details>)}
<div className="rowh"><h2>The HindWork Journal</h2></div><div className="grid">{[["Earn","How to price your first 5 gigs"],["Hire","Write a job post that gets great proposals"],["Skills","Five skills small businesses will pay for in 2026"]].map(([t,h],i)=><div className="card hov blog" key={h}><div className={"thumb t"+i}/><span className="pill">{t}</span><h3>{h}</h3></div>)}</div>
<section className="cta"><h2>Ready to take your work to the next level?</h2><p>Sign up with your phone number. No email needed.</p><Link href="/login" className="btn alt">Create free account</Link></section></>)}
