"use client";import {useEffect,useState} from "react";import {useParams} from "next/navigation";import {api,auth,toJob} from "../../../lib/api";import Proposal from "./Proposal";import Avatar from "../../../components/Avatar";import Icon,{I} from "../../../components/Icon";
export default function Job(){const {id}=useParams();const [j,setJ]=useState(null);const [err,setErr]=useState("");const [props,setProps]=useState(null);const [me,setMe]=useState(null);
useEffect(()=>{setMe(auth.user());api(`/jobs/${id}/`).then(d=>setJ(toJob(d))).catch(e=>setErr(e.message));api(`/jobs/${id}/proposals/`).then(setProps).catch(()=>{})},[id]);
const hire=pid=>api(`/proposals/${pid}/hire/`,{method:"POST"}).then(()=>location.href="/escrow").catch(e=>setErr(e.message));
if(err&&!j)return <p className="err">{err}</p>;if(!j)return <p>Loading...</p>;const open=j.status==="open";
return(<><div className="pg-head"><Avatar name={j.by||"E"} size={60} i={j.id}/><div style={{flex:1}}><h1 style={{margin:0}}>{j.title}</h1><p className="mute" style={{margin:"2px 0 6px"}}>Posted by {j.by}</p><span className="pill">{j.cat}</span><span className="pill">{j.lang}</span><span className={"badge "+(open?"ok":"")}>{j.status.replace("_"," ")}</span></div></div>
<div className="twocol"><div><div className="card"><h3>About this job</h3><p>{j.desc}</p>{j.skills.length>0&&<><h3 style={{marginTop:14}}>Skills needed</h3>{j.skills.map(s=><span className="pill" key={s}>{s}</span>)}</>}</div>
{err&&<p className="err">{err}</p>}
{props&&<><h2>Proposals ({props.length})</h2>{props.map(p=><div className="card row" key={p.id} style={{justifyContent:"space-between"}}><div className="row"><Avatar name={p.freelancer_name} i={p.id}/><div><b>{p.freelancer_name}</b><div className="mute">₹{p.price.toLocaleString("en-IN")} · {p.days} days</div><p className="mute" style={{margin:0}}>{p.message}</p></div></div>{open?<button className="btn sm" onClick={()=>hire(p.id)}>Hire</button>:<span className="badge">{p.status}</span>}</div>)}{!props.length&&<div className="card empty"><p className="mute">No proposals yet. Freelancers will appear here.</p></div>}</>}</div>
<div className="side"><div className="card"><span className="mute">Budget</span><h1 style={{margin:"0 0 6px"}}>₹{j.budget.toLocaleString("en-IN")}</h1><div className="row mute"><Icon d={I.clock} size={16}/>{j.days} days to deliver</div><div className="wait" style={{marginTop:12}}>🔒 Escrow protected. Money is released only after approval.</div></div>
{!props&&me?.role!=="employer"&&open&&<Proposal id={j.id} budget={j.budget} days={j.days}/>}{!me&&<p className="mute">Log in as a freelancer to apply.</p>}</div></div></>)}
